#!/bin/bash
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
LIGHT='\033[0;37m'

# // Html
randomNum=$((RANDOM % 6 + 1))
rm -rf /usr/share/nginx/html
wget -q -P /usr/share/nginx https://raw.githubusercontent.com/Manpokr/multi/main/html/html${randomNum}.zip 
unzip -o /usr/share/nginx/html${randomNum}.zip -d /usr/share/nginx/html 
rm -f /usr/share/nginx/html${randomNum}.zip*
cd
echo -e " Done Html"
sleep2
